# Generated by Django 2.0.4 on 2018-04-13 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoicedetail_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemgroup',
            name='order',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='並び順'),
            preserve_default=False,
        ),
    ]
